// React/src/App.tsx
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import DataGrid, {
  Editing, Column, Lookup, type DataGridTypes,
} from 'devextreme-react/data-grid';
import './App.css';
import ArrayStore from 'devextreme/data/array_store';
import { type DataSourceOptions } from 'devextreme-react/common/data';
import service, { type City, type Employee } from './data';
import MultipleDropDownBox from './components/MultipleDropDownBox';

const dataSource: Employee[] = service.getEmployees();

const statesStore = new ArrayStore({
  data: service.getStates(),
  key: 'ID',
});

const citiesStore = new ArrayStore({
  data: service.getCities(),
  key: 'ID',
});

function getFilteredCities(cellInfo: DataGridTypes.ColumnEditCellTemplateData<Employee, number>, citiesStore: ArrayStore): DataSourceOptions {
  return {
    store: citiesStore,
    filter: (data: City) => (cellInfo.data?.StateID && cellInfo.data?.StateID?.length > 0
      ? cellInfo.data?.StateID.includes(data.StateID)
      : true),
  };
}

async function setStateValue(this: DataGridTypes.Column<Employee, number>, rowData: Employee, value: number[], currentRowData: Employee): Promise<void> {
  rowData.CityID = [];
  await this.defaultSetCellValue?.(rowData, value, currentRowData);
}

function arrayCellTemplate(container: HTMLElement, options: DataGridTypes.ColumnCellTemplateData<Employee, number>): void {
  const noBreakSpace = '\u00A0';
  const text = (options.value || [])
    .map((element: number) => options.column.lookup?.calculateCellValue?.(element) as string || '')
    .join(', ');
  container.textContent = text || noBreakSpace;
  container.title = text;
}

function renderMultipleDropDownBox(
  currentValue: number[],
  setValue: (value: number[]) => void,
  dataSource: ArrayStore | DataSourceOptions,
): JSX.Element {
  return (
    <MultipleDropDownBox
      dataSource={dataSource}
      value={currentValue}
      setValue={setValue}
    />
  );
}

function renderStateDropDownBox(e: DataGridTypes.ColumnEditCellTemplateData<Employee, number>): JSX.Element {
  const { setValue } = e;
  return renderMultipleDropDownBox(
    e.value,
    setValue,
    statesStore,
  );
}

function renderCityDropDownBox(e: DataGridTypes.ColumnEditCellTemplateData<Employee, number>): JSX.Element {
  const { setValue } = e;
  return renderMultipleDropDownBox(
    e.value,
    setValue,
    getFilteredCities(e, citiesStore),
  );
}

function App(): JSX.Element {
  return (
    <div className="App">
      <DataGrid dataSource={dataSource}>
        <Editing
          mode="row"
          allowUpdating={true}
          allowAdding={true}>
        </Editing>
        <Column
          dataField="StateID"
          caption="State"
          setCellValue={setStateValue}
          cellTemplate={arrayCellTemplate}
          editCellRender={renderStateDropDownBox}>
          <Lookup dataSource={statesStore} displayExpr="Name" valueExpr="ID" />
        </Column>
        <Column
          dataField="CityID"
          caption="City"
          cellTemplate={arrayCellTemplate}
          editCellRender={renderCityDropDownBox}>
          <Lookup dataSource={citiesStore} displayExpr="Name" valueExpr="ID" />
        </Column>
      </DataGrid>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { DataSource, ArrayStore } from 'devextreme-angular/common/data';
import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
import dxDataGrid from 'devextreme/ui/data_grid';
import dxDropDownBox from 'devextreme/ui/drop_down_box';
import {
  AppService, Employee, State, City,
} from './app.service';
import { CityDropDownInfo, EditCellInfo } from './app.types';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [AppService],
})
export class AppComponent {
  data: Employee[];

  states: State[];

  cities: City[];

  stateDataGrid: any;

  cityDataGrid: any;

  cityDropDownInfo: CityDropDownInfo = {
    StateID: null,
    ds: null,
  };

  constructor(private readonly service: AppService) {
    this.data = service.getEmployees();
    this.states = service.getStates();
    this.cities = service.getCities();
  }

  getFilteredCities = (options: EditCellInfo<Employee, number>): { store: City[]; filter: [string, string, number[]] | null } => ({
    store: this.cities,
    filter: options.data ? ['StateID', '=', options.data.StateID] : null,
  });

  getCityDropDownDs(cellInfo: DxDataGridTypes.ColumnEditCellTemplateData<Employee, number>): DataSource {
    const currStateID = cellInfo.row.data.StateID || [-1];
    const prevStateID = this.cityDropDownInfo.StateID;
    if (!this.isArrEqual(prevStateID, currStateID)) {
      this.cityDropDownInfo = {
        StateID: currStateID,
        ds: new DataSource({
          store: new ArrayStore({
            data: this.cities,
            key: 'ID',
          }),
          filter: (data: City) => (cellInfo.row.data.StateID ? cellInfo.row.data.StateID.includes(data.StateID) : true),
        }),
      };
    }

    return this.cityDropDownInfo.ds ?? new DataSource({ store: [] });
  }

  isArrEqual(a: number[] | null, b: number[]): boolean {
    return (
      Array.isArray(a)
      && Array.isArray(b)
      && a.length === b.length
      && a.every((val, index) => val === b[index])
    );
  }

  async setStateValue(this: DxDataGridTypes.Column<Employee, number>, rowData: Employee, value: number[], currentRowData: Employee): Promise<void> {
    rowData.CityID = [];
    await this.defaultSetCellValue?.(rowData, value, currentRowData);
  }

  arrayCellTemplate(container: HTMLElement, options: DxDataGridTypes.ColumnCellTemplateData<Employee, number>): void {
    const noBreakSpace = '\u00A0';
    const text = (options.value || [])
      .map((element: number): string => options.column.lookup?.calculateCellValue?.(element) as string).join(', ');
    container.textContent = text || noBreakSpace;
    container.title = text;
  }

  onClick(dataGrid: dxDataGrid, cellInfo: DxDataGridTypes.ColumnEditCellTemplateData<Employee, number>, dropDownBox: dxDropDownBox): void {
    const selectedKeys = dataGrid.getSelectedRowKeys();
    cellInfo.setValue(selectedKeys);
    dropDownBox.close();
  }
}

<div id="data-grid-demo">
  <dx-data-grid [dataSource]="data">
    <dxo-editing mode="row" [allowUpdating]="true" [allowAdding]="true">
    </dxo-editing>

    <dxi-column
      dataField="StateID"
      caption="State"
      [setCellValue]="setStateValue"
      [cellTemplate]="arrayCellTemplate"
      editCellTemplate="multipleDropDownBoxStateTemplate"
    >
      <dxo-lookup [dataSource]="states" valueExpr="ID" displayExpr="Name">
      </dxo-lookup>
    </dxi-column>
    <dxi-column
      dataField="CityID"
      caption="City"
      [cellTemplate]="arrayCellTemplate"
      editCellTemplate="multipleDropDownBoxCityTemplate"
    >
      <dxo-lookup
        [dataSource]="getFilteredCities"
        valueExpr="ID"
        displayExpr="Name"
      >
      </dxo-lookup>
    </dxi-column>
    <div *dxTemplate="let cellInfo of 'multipleDropDownBoxStateTemplate'">
      <dx-drop-down-box
        [dataSource]="states"
        [(value)]="cellInfo.value"
        displayExpr="Name"
        valueExpr="ID"
        contentTemplate="contentTemplate"
      >
        <div *dxTemplate="let e of 'contentTemplate'">
          <dx-data-grid
            #dataGrid
            [dataSource]="states"
            keyExpr="ID"
            [selectedRowKeys]="cellInfo.value"
            [hoverStateEnabled]="true"
            (onSelectionChanged)="onSelectionChanged($event)"
          >
            <dxi-column dataField="ID"></dxi-column>
            <dxi-column dataField="Name"></dxi-column>
            <dxo-selection mode="multiple"></dxo-selection>
          </dx-data-grid>
          <ng-container
            [ngTemplateOutlet]="dropDownSaveBtn"
            [ngTemplateOutletContext]="{dataGrid: dataGrid.instance,cellInfo: cellInfo, dropDownBox: e.component}"
          >
          </ng-container>
        </div>
      </dx-drop-down-box>
    </div>

    <div *dxTemplate="let cellInfo of 'multipleDropDownBoxCityTemplate'">
      <dx-drop-down-box
        [dataSource]="getCityDropDownDs(cellInfo)"
        [(value)]="cellInfo.value"
        displayExpr="Name"
        valueExpr="ID"
        contentTemplate="contentTemplate"
      >
        <div *dxTemplate="let e of 'contentTemplate'">
          <dx-data-grid
            #dataGrid
            [dataSource]="getCityDropDownDs(cellInfo)"
            [selectedRowKeys]="cellInfo.value"
            [hoverStateEnabled]="true"
            (onSelectionChanged)="onSelectionChanged($event)"
          >
            <dxi-column dataField="ID"></dxi-column>
            <dxi-column dataField="Name"></dxi-column>
            <dxo-selection mode="multiple"></dxo-selection>
          </dx-data-grid>
          <ng-container
            [ngTemplateOutlet]="dropDownSaveBtn"
            [ngTemplateOutletContext]="{dataGrid: dataGrid.instance,cellInfo: cellInfo, dropDownBox: e.component}"
          >
          </ng-container>
        </div>
      </dx-drop-down-box>
    </div>
  </dx-data-grid>
</div>

<ng-template
  #dropDownSaveBtn
  let-cellInfo="cellInfo"
  let-dataGrid="dataGrid"
  let-dropDownBox="dropDownBox"
>
  <dx-button
    text="Apply"
    (onClick)="onClick(dataGrid, cellInfo, dropDownBox)"
  ></dx-button>
</ng-template>
