// React/src/App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import React from 'react';
import DataGrid, { Editing, Column, Lookup } from 'devextreme-react/data-grid';
import './App.css';
import service from './data'
import MultipleDropDownBox from './components/MultipleDropDownBox';
import DataSource from 'devextreme/data/data_source'
import ArrayStore from 'devextreme/data/array_store';

const dataSource = service.getEmployees(),
  states = service.getStates(),
  cities = service.getCities();

function App() {
  function renderMultipleDropDownBox(value, setValue, dataSource) {
    return <MultipleDropDownBox dataSource={dataSource} value={value} setValue={setValue} />
  }
  
  return (
    <div className="App">
      <DataGrid dataSource={dataSource}>
        <Editing
          mode="row"
          allowUpdating={true}
          allowAdding={true}>
        </Editing>
        <Column
          dataField="StateID"
          caption="State"
          setCellValue={setStateValue}
          cellTemplate={arrayCellTemplate}
          editCellRender={({ value, setValue }) => renderMultipleDropDownBox(value, setValue, states)}>
          <Lookup dataSource={states} displayExpr="Name" valueExpr="ID" />
        </Column>
        <Column
          dataField="CityID"
          caption="City"
          cellTemplate={arrayCellTemplate}
          editCellRender={
            ({ value, setValue, data: { StateID } }) => 
            renderMultipleDropDownBox(
              value,
              setValue,
              getCitySelectBoxDs(StateID)
            )
          }>
          <Lookup dataSource={getFilteredCities} displayExpr="Name" valueExpr="ID" />
        </Column>
      </DataGrid>
    </div>
  );
}

function getFilteredCities(options) {
  return {
    store: cities,
    filter: options.data ? ["StateID", "=", options.data.StateID] : null
  };
}

function getCitySelectBoxDs(filterValue) {
  return new DataSource({
    store: new ArrayStore({
      data: cities,
      key: "ID"
    }),
    filter: function (dataItem) {
      return filterValue.includes(dataItem.StateID)
    }
  })
}

function setStateValue(rowData, value) {
  rowData.CityID = [];
  this.defaultSetCellValue(rowData, value);
}

function arrayCellTemplate(container, options) {
  var noBreakSpace = "\u00A0",
    text = (options.value || [])
      .map(element => {
        return options.column.lookup.calculateCellValue(element);
      })
      .join(", ");
  container.textContent = text || noBreakSpace;
  container.title = text;
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Service, Employee, State, City } from "./app.service";
import DataSource from "devextreme/data/data_source";
import ArrayStore from "devextreme/data/array_store";
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service]
})
export class AppComponent {
  data: Employee[];
  states: State[];
  cities: City[];

  cityDropDownInfo = {
    StateID: null,
    ds: null
  };

  constructor(private service: Service) {
    this.data = service.getEmployees();
    this.states = service.getStates();
    this.cities = service.getCities();

    this.getFilteredCities = this.getFilteredCities.bind(this);
  }

  getFilteredCities(options) {
    return {
      store: this.cities,
      filter: options.data ? ["StateID", "=", options.data.StateID] : null
    };
  }

  getCityDropDownDs(cellInfo) {
    let currStateID = cellInfo.row.data.StateID,
      prevStateID = this.cityDropDownInfo.StateID;

    if (!this.isArrEqual(prevStateID, currStateID)) {
      this.cityDropDownInfo = {
        StateID: cellInfo.row.data.StateID,
        ds: new DataSource({
          store: new ArrayStore({
            data: this.cities,
            key: "ID"
          }),
          filter: function(data) {
            return cellInfo.row.data.StateID.includes(data.StateID);
          }
        })
      };
    }

    return this.cityDropDownInfo.ds;
  }

  isArrEqual(a, b) {
    return (
      Array.isArray(a) &&
      Array.isArray(b) &&
      a.length === b.length &&
      a.every((val, index) => val === b[index])
    );
  }

  setStateValue(rowData: any, value: any): void {
    rowData.CityID = null;
    (<any>this).defaultSetCellValue(rowData, value);
  }

  arrayCellTemplate(container, options) {
    var noBreakSpace = "\u00A0",
      text = (options.value || [])
        .map(element => {
          return options.column.lookup.calculateCellValue(element);
        })
        .join(", ");
    container.textContent = text || noBreakSpace;
    container.title = text;
  }

  onSelectionChanged(e) {
    e.component.option("value", e.selectedRowKeys);
  }

  onClick(dataGrid, cellInfo, dropDownBox) {
    let selectedKeys = dataGrid.getSelectedRowKeys();
    cellInfo.setValue(selectedKeys);
    dropDownBox.close();
  }
}

<div id="data-grid-demo">
  <dx-data-grid [dataSource]="data">
    <dxo-editing mode="row" [allowUpdating]="true" [allowAdding]="true">
    </dxo-editing>

    <dxi-column
      dataField="StateID"
      caption="State"
      [setCellValue]="setStateValue"
      [cellTemplate]="arrayCellTemplate"
      editCellTemplate="multipleDropDownBoxStateTemplate"
    >
      <dxo-lookup [dataSource]="states" valueExpr="ID" displayExpr="Name">
      </dxo-lookup>
    </dxi-column>
    <dxi-column
      dataField="CityID"
      caption="City"
      [cellTemplate]="arrayCellTemplate"
      editCellTemplate="multipleDropDownBoxCityTemplate"
    >
      <dxo-lookup
        [dataSource]="getFilteredCities"
        valueExpr="ID"
        displayExpr="Name"
      >
      </dxo-lookup>
    </dxi-column>
    <div *dxTemplate="let cellInfo of 'multipleDropDownBoxStateTemplate'">
      <dx-drop-down-box
        [dataSource]="states"
        [(value)]="cellInfo.value"
        displayExpr="Name"
        valueExpr="ID"
        contentTemplate="contentTemplate"
      >
        <div *dxTemplate="let e of 'contentTemplate'">
          <dx-data-grid
            #dataGrid
            [dataSource]="states"
            keyExpr="ID"
            [selectedRowKeys]="cellInfo.value"
            [hoverStateEnabled]="true"
            (onSelectionChanged)="onSelectionChanged($event)"
          >
            <dxi-column dataField="ID"></dxi-column>
            <dxi-column dataField="Name"></dxi-column>
            <dxo-selection mode="multiple"></dxo-selection>
          </dx-data-grid>
          <ng-container
            [ngTemplateOutlet]="dropDownSaveBtn"
            [ngTemplateOutletContext]="{dataGrid: dataGrid.instance,cellInfo: cellInfo, dropDownBox: e.component}"
          >
          </ng-container>
        </div>
      </dx-drop-down-box>
    </div>

    <div *dxTemplate="let cellInfo of 'multipleDropDownBoxCityTemplate'">
      <dx-drop-down-box
        [dataSource]="getCityDropDownDs(cellInfo)"
        [(value)]="cellInfo.value"
        displayExpr="Name"
        valueExpr="ID"
        contentTemplate="contentTemplate"
      >
        <div *dxTemplate="let e of 'contentTemplate'">
          <dx-data-grid
            #dataGrid
            [dataSource]="getCityDropDownDs(cellInfo)"
            [selectedRowKeys]="cellInfo.value"
            [hoverStateEnabled]="true"
            (onSelectionChanged)="onSelectionChanged($event)"
          >
            <dxi-column dataField="ID"></dxi-column>
            <dxi-column dataField="Name"></dxi-column>
            <dxo-selection mode="multiple"></dxo-selection>
          </dx-data-grid>
          <ng-container
            [ngTemplateOutlet]="dropDownSaveBtn"
            [ngTemplateOutletContext]="{dataGrid: dataGrid.instance,cellInfo: cellInfo, dropDownBox: e.component}"
          >
          </ng-container>
        </div>
      </dx-drop-down-box>
    </div>
  </dx-data-grid>
</div>

<ng-template
  #dropDownSaveBtn
  let-cellInfo="cellInfo"
  let-dataGrid="dataGrid"
  let-dropDownBox="dropDownBox"
>
  <dx-button
    text="Apply"
    (onClick)="onClick(dataGrid, cellInfo, dropDownBox)"
  ></dx-button>
</ng-template>
