// React/src/orig_App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import React from 'react';
import DataGrid, { Editing, Column, Lookup } from 'devextreme-react/data-grid';
import './App.css';
import service from './data'
import MultipleDropDownBox from './components/MultipleDropDownBox';
import ArrayStore from 'devextreme/data/array_store';

const dataSource = service.getEmployees(),
  states = new ArrayStore({
    data: service.getStates(),
    key: "ID"
  }),
  cities = new ArrayStore({
    data: service.getCities(),
    key: "ID"
  });

function App() {
  function renderMultipleDropDownBox(value, setValue, dataSource) {
    return <MultipleDropDownBox dataSource={dataSource} value={value} setValue={setValue} />
  }

  function renderCityDropDownBox(e) {
    const {value, setValue} = e;
    return renderMultipleDropDownBox(
      value,
      setValue,
      getFilteredCities(e)
    )
  }
  
  return (
    <div className="App">
      <DataGrid dataSource={dataSource}>
        <Editing
          mode="row"
          allowUpdating={true}
          allowAdding={true}>
        </Editing>
        <Column
          dataField="StateID"
          caption="State"
          setCellValue={setStateValue}
          cellTemplate={arrayCellTemplate}
          editCellRender={({ value, setValue }) => renderMultipleDropDownBox(value, setValue, states)}>
          <Lookup dataSource={states} displayExpr="Name" valueExpr="ID" />
        </Column>
        <Column
          dataField="CityID"
          caption="City"
          cellTemplate={arrayCellTemplate}
          editCellRender={renderCityDropDownBox}>
          <Lookup dataSource={getFilteredCities} displayExpr="Name" valueExpr="ID" />
        </Column>
      </DataGrid>
    </div>
  );
}

function getFilteredCities(options) {
  return {
    store: cities,
    filter: options.data ? ["StateID", "=", options.data.StateID] : null,
  };
}

function setStateValue(rowData, value) {
  rowData.CityID = [];
  this.defaultSetCellValue(rowData, value);
}

function arrayCellTemplate(container, options) {
  var noBreakSpace = "\u00A0",
    text = (options.value || [])
      .map(element => {
        return options.column.lookup.calculateCellValue(element);
      })
      .join(", ");
  container.textContent = text || noBreakSpace;
  container.title = text;
}

export default App;

// Angular/src/app/orig_app.component.ts
import { Component } from '@angular/core';
import { Service, Employee, State, City } from "./app.service";
import DataSource from "devextreme/data/data_source";
import ArrayStore from "devextreme/data/array_store";
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service]
})
export class AppComponent {
  data: Employee[];
  states: State[];
  cities: City[];

  cityDropDownInfo = {
    StateID: null,
    ds: null
  };

  constructor(private service: Service) {
    this.data = service.getEmployees();
    this.states = service.getStates();
    this.cities = service.getCities();

    this.getFilteredCities = this.getFilteredCities.bind(this);
  }

  getFilteredCities(options) {
    return {
      store: this.cities,
      filter: options.data ? ["StateID", "=", options.data.StateID] : null
    };
  }

  getCityDropDownDs(cellInfo) {
    let currStateID = cellInfo.row.data.StateID,
      prevStateID = this.cityDropDownInfo.StateID;

    if (!this.isArrEqual(prevStateID, currStateID)) {
      this.cityDropDownInfo = {
        StateID: cellInfo.row.data.StateID,
        ds: new DataSource({
          store: new ArrayStore({
            data: this.cities,
            key: "ID"
          }),
          filter: function(data) {
            return cellInfo.row.data.StateID.includes(data.StateID);
          }
        })
      };
    }

    return this.cityDropDownInfo.ds;
  }

  isArrEqual(a, b) {
    return (
      Array.isArray(a) &&
      Array.isArray(b) &&
      a.length === b.length &&
      a.every((val, index) => val === b[index])
    );
  }

  setStateValue(rowData: any, value: any): void {
    rowData.CityID = [];
    (<any>this).defaultSetCellValue(rowData, value);
  }

  arrayCellTemplate(container, options) {
    var noBreakSpace = "\u00A0",
      text = (options.value || [])
        .map(element => {
          return options.column.lookup.calculateCellValue(element);
        })
        .join(", ");
    container.textContent = text || noBreakSpace;
    container.title = text;
  }


  onClick(dataGrid, cellInfo, dropDownBox) {
    let selectedKeys = dataGrid.getSelectedRowKeys();
    cellInfo.setValue(selectedKeys);
    dropDownBox.close();
  }
}
